### ISSUE TITLE
Make design Google doc in readme 644 permissions

### ISSUE THREAD

**Issue by rothgar** [kubernetes/cluster-registry#1]
I can't open the Google doc in the readme. Please update permissions so anyone with the link can read it.

**Comment by perotinus** [comment]
Are you a member of the [kubernetes-dev](https://groups.google.com/d/msg/kubernetes-dev) mailing list? I'm not sure exactly how to share the link outside of the organization I'm a part of, but if you join that group you should get access.

**Comment by perotinus** [comment]
Closing this. Feel free to reopen if you're still having problems.
