### ISSUE TITLE
Write a design document

### ISSUE THREAD

**Issue by perotinus** [kubernetes/cluster-registry#10]
Now that the cluster registry prototype is done, we should write a design based on this knowledge and circulate it more broadly.

**Comment by pmorie** [comment]
A walkthrough would also be helpful, when we feel there is something
substantial to demonstrate to people.

**Comment by perotinus** [comment]
Created #11 to track.

**Comment by perotinus** [comment]
Project plan is being discussed [here](https://docs.google.com/document/d/1bVvq9lDIbE-Glyr6GkSGWYkLb2cCNk9bR8LL7Wm-L6g/edit).

Please join [kubernetes-dev](https://groups.google.com/forum/#!forum/kubernetes-dev) if you don't have access.

**Comment by perotinus** [comment]
https://github.com/kubernetes/community/pull/1324 will commit this to the community repo.

**Comment by perotinus** [comment]
https://github.com/kubernetes/community/pull/1325 is committed.
