### ISSUE TITLE
Add crinit aggregated unit tests

### ISSUE THREAD

**Issue by font** [kubernetes/cluster-registry#114]
Add `crinit aggregated` unit tests similar to `standalone_test.go`. This could also include refactoring the common unit test code.

/sig multicluster

**Comment by onyiny-ang** [comment]
@font  @perotinus Has this issue been sufficiently addressed by #170 or is there additional functionality that I can work on to close out this issue? I'm looking for some more work and am wondering if this might be a good place to start (again).

**Comment by perotinus** [comment]
Note that this issue is no longer applicable because of the CRD migration done in #225, which removes `crinit` and the standalone API server.
