### ISSUE TITLE
crinit "Waiting for API server" doesn't work in some cases

### ISSUE THREAD

**Issue by perotinus** [kubernetes/cluster-registry#118]
/sig multicluster

`crinit`'s waiting for the API server to be ready does not usually (and sometimes cannot) work.

- NodePort services, which are not accessible outside of the cluster if the node is not publicly accessible
- aggregated services, where conceptually the "ready" check should be that the user can get clusters from the aggregator.

**Comment by font** [comment]
Yes, thanks for filing this!
