### ISSUE TITLE
Make sure API name is appropriate

### ISSUE THREAD

**Issue by perotinus** [kubernetes/cluster-registry#121]
/sig multicluster

@madhusudancs brought up in #117 that using `clusterregistry.k8s.io` may not be appropriate; we may need to find a different name that does not contain `k8s.io`. Follow up on this.

**Comment by perotinus** [comment]
/cc @kubernetes/api-approvers

Is it appropriate to use `clusterregistry.k8s.io` for this, or should we find an alternative name? I believe there is precedent for using a `k8s.io` name in the service catalog API.

**Comment by perotinus** [comment]
Reached out to sig-arch about this.

**Comment by bgrant0607** [comment]
It's a subproject of the Kubernetes project, so use of the .k8s.io suffix is ok. 

It's more debatable whether it should be a clusterregistry or apiregistry. :-)

**Comment by madhusudancs** [comment]
@bgrant0607 I am curious. Why `apiregistry`? :)

**Comment by perotinus** [comment]
This has come up again on a thread in sig-multicluster: https://groups.google.com/forum/#!topic/kubernetes-sig-multicluster/GwyZqD3dNKo

**Comment by bgrant0607** [comment]
@perotinus @csbell Has the API group and/or resource type name been resolved?

**Comment by perotinus** [comment]
@bgrant0607 @csbell Yes. We stuck with `clusterregistry` in the absence of an alternative that had enough sticking power.
