### ISSUE TITLE
Provide DoS protection in cluster registry API server 

### ISSUE THREAD

**Issue by madhusudancs** [kubernetes/cluster-registry#125]
Provide some form of support to prevent DoS attacks on cluster registry API server. We should probably piggyback on https://github.com/kubernetes/kubernetes/issues/22679

cc @perotinus 

/sig multicluster

**Comment by perotinus** [comment]
Note that this issue is no longer applicable because of the CRD migration done in #225, which removes `crinit` and the standalone API server.
