### ISSUE TITLE
We should release 0.0.1 of cluster-registry

### ISSUE THREAD

**Issue by pmorie** [kubernetes/cluster-registry#138]
I don't see any reason that we can't release 0.0.1 now.  I am sure there is work to do to have CI build the image (I would love to be wrong about that). However - we now have integration tests for the client and API resources.  My experience with getting to an initial alpha release of other projects in the past has been that there is not a large payoff to making things any better than 'good enough'.  I think we are at the 'good enough' bar for 0.0.1 now, and we can make improvements (include non-backward-compatible changes) in subsequent releases (which I would suggest that we make weekly).

Posting this issue to see how people feel about this, and to hopefully find a champion or two (ahem, @font and @perotinus) to finalize any remaining work items associated with stuff like building and pushing images.

WDYT?   

/sig multicluster

**Comment by madhusudancs** [comment]
+1. For some reason I was under the impression that this had already happened :)

Also, why 0.0.1 and not 0.1.0? Haven't we made enough progress to call this 0.1.0?

**Comment by perotinus** [comment]
@madhusudancs I'd like to get a 0.0.1 out there before 0.1.0, since it's a first pass at trying out a release process. I suppose it's really a cosmetic point, though: I have no objection to a 0.1.0 coming soon after, or even being first.

**Comment by pmorie** [comment]
0.1.0 is supposed to indicate beta status

**Comment by perotinus** [comment]
Just released https://github.com/kubernetes/cluster-registry/releases/tag/v0.0.1.

**Comment by madhusudancs** [comment]
Ok fair enough. Whatever works.
