### ISSUE TITLE
Support dynamic configuration of cluster registry API server via ComponentConfig

### ISSUE THREAD

**Issue by madhusudancs** [kubernetes/cluster-registry#142]
We should probably piggyback on what kube-apiserver does.

/sig multicluster

**Comment by perotinus** [comment]
+1. I'd love to do this. I haven't heard of much movement to do this in the kube-apiserver, but I haven't looked that recently.

**Comment by perotinus** [comment]
Note that this issue is no longer applicable because of the CRD migration done in #225, which removes `crinit` and the standalone API server.
