### ISSUE TITLE
Ensure resiliency in the face of hosting cluster health problems

### ISSUE THREAD

**Issue by marun** [kubernetes/cluster-registry#154]
Given that the cluster registry is intended to be a foundational service for applications that target multiple clusters, it may be worth considering what kind of reliability guarantees would be desired by those applications.  It seems interesting to ensure the resiliency of the registry to health problems in the hosting cluster, e.g. by deploying APIs in an HA configuration across multiple clusters.  

Given that etcd cluster members have upper bounds on allowable latency, the hosting clusters of an etcd cluster spanning those clusters would need to be located in close proximity (likely in the same datacenter) which may limit potential fault tolerance.  If greater fault tolerance is required, it may be worth considering the use of a backing store that can reliably span clusters with greater inter-cluster communication latency.

/sig multicluster

**Comment by marun** [comment]
cc: @pmorie @perotinus

**Comment by perotinus** [comment]
@marun and I chatted about this a bit yesterday. I agree that this is something that needs to be addressed, but given the move towards tying the k8s API machinery more closely to etcd, it seems like it might be difficult to achieve enough resiliency using the k8s API machinery and etcd. That said, we don't have a good handle on what users want or need, so it seems like a good path for now is to assume that etcd configured regionally would be acceptable, and wait for a users to present compelling reasons to make it even more highly available.
