### ISSUE TITLE
Update Gopkg.toml to not constrain to specific dependency revisions

### ISSUE THREAD

**Issue by perotinus** [kubernetes/cluster-registry#190]
/sig multicluster

Constraining dependency versions in `Gopkg.toml` to specific revisions is almost always an [antipattern](https://golang.github.io/dep/docs/Gopkg.toml.html#revision), according to the `dep` documentation. We should move away from this.

**Comment by perotinus** [comment]
One specific negative consequence of using this pattern is that it makes it more difficult for other projects to vendor in the cluster registry, cf. #173

**Comment by font** [comment]
Fixed by #201.
