### ISSUE TITLE
Cluster API issues

### ISSUE THREAD

**Issue by perotinus** [kubernetes/cluster-registry#20]
@pmorie raised a few issues in #16 about the cluster registry API that were not addressed:

- [x] being more explicit about how credentials are handled/whether credentials should be stored
  - work here is waiting for input from SIG-auth about how to handle cluster credentials in the cluster registry
- [x] optional fields should be pointers
  - this seems reasonable, but would like to discuss with sig-arch and/or sig-api-machinery to make sure

Besides this, there are a few issues from the cluster registry API design that also need to be addressed:
- [x] using a stronger type for the Kubernetes API server info
  - this was going to be a copy of `api.Endpoints` from k8s, for reasons described [here](https://docs.google.com/a/google.com/document/d/1Oi9EO3Jwtp69obakl-9YpLkP764GZzsz95XJlX1a960/edit?disco=AAAABFxkK0A), but after pushback more discussion is needed
- [x] spec/status field names/presence
  - this is waiting on discussions with sig-arch and/or sig-api-machinery
- [x] `CABundle` in `KubeAPIServer`
  - waiting for response on comment

And an issue from #29:
- [x] figure out motivation for or remove `CloudProvider` field

cf https://docs.google.com/a/google.com/document/d/1Oi9EO3Jwtp69obakl-9YpLkP764GZzsz95XJlX1a960/edit?disco=AAAABFxkK0A

cc @pmorie @quinton-hoole

**Comment by perotinus** [comment]
cc @madhusudancs

**Comment by perotinus** [comment]
Updates for the above points:

1. After discussion with SIG-auth, we made the decision to go with a generic type for auth, and to heavily discourage storing credentials in the cluster registry
3. We will use an Endpoints object copied from the k8s API.
4. We resolved these discussions in favor of spec/status
5. Assuming lazy consensus, we are going with what's there now.

**Comment by madhusudancs** [comment]
I made this comment on the PR #31. But I am noticing this issue now. So copying the comment here. 

I am really confused. Copying Endpoints object seems incorrect. For example, what purpose would EndpointPort.Protocol serve? If anything, this should mirror what's in federation now. I can't see all the fields in Kubernetes core api/v1.Endpoint being appropriate here.

**Comment by madhusudancs** [comment]
I think if we are copying anything, what's in federation today is far more useful than copying `api/v1.Endpoint`.

**Comment by perotinus** [comment]
I believe that all of these issues have been addressed. Closing.
