### ISSUE TITLE
Transform this repo from a custom API server to a set of CRDs

### ISSUE THREAD

**Issue by pmorie** [kubernetes/cluster-registry#215]
As @perotinus has outlined [here](https://docs.google.com/document/d/1FhoxzYUJ4qiyZ4qA8LE5zgCO4jUihiDUlbttvLlnRmk/edit#), there are a number of reasons that using CRDs as the basis of cluster-registry.

I think we should move toward using CRDs as the basis for this repository. I imagine that after that transformation, we probably have 2 (possibly 3) repos:

- `cluster-registry` holds:
  - the CRD definitions
  - any future validating/mutating webhook server
  - a tiny `crinit` binary that installs the CRDs
- `cluster-registry-api` holds the Go API
- `cluster-registry-client-go` holds the generated Go client

We could collapse the `cluster-registry-api` repo and `cluster-registry-client-go` repo into just `cluster-registry-client-go` initially, if useful.

/sig multicluster

**Comment by pmorie** [comment]
I think if we adopt CRD, we should probably cut a special branch that has the existing code and then do a hard reset in master to a new state that has the right stuff.

**Comment by pmorie** [comment]
Prototyping this in github.com/pmorie/cluster-registry-crd

**Comment by perotinus** [comment]
@pmorie Thank you for taking this on! Looking forward to seeing this get fleshed out.

**Comment by madhusudancs** [comment]
Thanks @pmorie. Can we prioritize this? Let me know if you need something from me to get this done ASAP.

**Comment by sdake** [comment]
@pmorie sorry to bother - know your busy - we depend on this repo at the moment in https://github.com/istio/istio.  I don't mind the change to CRD, seems to make good logical sense to me.  I am curious if you have a time line so we can make a decision as to how to handle this dependency?

Cheers
-steve

**Comment by perotinus** [comment]
@sdake Apologies for not writing down a timeline, but this was done in #225.
