### ISSUE TITLE
Determine name of 'public' namespace for globally accessible cluster records

### ISSUE THREAD

**Issue by pmorie** [kubernetes/cluster-registry#221]
As part of #220, we decided that there should be a reserved namespace designated as being for 'public' cluster records that anyone should be allowed to see. This issue is to determine the name of that namespace.

**Comment by quinton-hoole** [comment]
multicluster-public and multicluster-system would be my preference.

**Comment by perotinus** [comment]
There is a thread about this on the SIG list: https://groups.google.com/forum/#!topic/kubernetes-sig-multicluster/8u-li_ZJpDI
