### ISSUE TITLE
`crinit standalone init mycr  mycluster.icp-context` hang

### ISSUE THREAD

**Issue by gyliu513** [kubernetes/cluster-registry#223]
/sig multicluster

```
root@gyliu-ubuntu-1:~/gyliu/mc# ./crinit standalone init mycr  mycluster.icp-context
Creating a namespace clusterregistry for the cluster registry... done
Creating cluster registry API server service...............................................................................................
```

Which log shall I check for such condition?

**Comment by perotinus** [comment]
You may be able to see more logs if you run the command with `-v=10`, though I'm not sure that they will have the information that you need.

Note, though, that this issue is no longer applicable because of the CRD migration done in #225.

**Comment by gyliu513** [comment]
Thanks @perotinus , will check
