### ISSUE TITLE
Wrong cp command in the examples/samplecontainer/README.md

### ISSUE THREAD

**Issue by roytman** [kubernetes/cluster-registry#226]
/sig multicluster

The file examples/samplecontainer/README.md has the following command
`
cp "$(bazel info bazel-bin)/cmd/clusterregistry/clusterregistry" \
  "$(bazel info bazel-bin)/examples/slackcontroller/slackcontroller" \
  ./contents
`

However, the  binaries are located in the OS and ARCH dependent path. 

On my MAC it is 
`$(bazel info bazel-bin)/cmd/clusterregistry/darwin_amd64_stripped/clusterregistry"` and
`$(bazel info bazel-bin)/examples/slackcontroller/darwin_amd64_stripped/slackcontroller"`

**Comment by perotinus** [comment]
This issue is no longer applicable because of the CRD migration done in #225.
