### ISSUE TITLE
Determine whether generated code needs to be checked in

### ISSUE THREAD

**Issue by perotinus** [kubernetes/cluster-registry#24]
From a comment on #21, there might be reason to check in the generated artifacts to enable people who do not use bazel to depend on this repository; and perhaps to make the test infrastructure easier to wrangle. I am quite opposed to checking in artifacts unless it really is blocking a workflow, so this issue is tracking whether enough need to outweigh the pain of checked-in generated code.

If this is causing you problems, please bump this issue!

**Comment by pmorie** [comment]
I have a strong preference toward:

- Checking in any generated code
- Checking in vendored dependencies

**Comment by ericchiang** [comment]
Regardless of checking in vendored code, I would like to stress that cluster-registry must check in generated code to be compatible with non-bazel based project.

As someone who needs to use the cluster-registry client and coming from an org that hasn't used bazel in the past, this is a blocker.

**Comment by pmorie** [comment]
Yes, I would prefer to check in any generated code as well.

**Comment by ericchiang** [comment]
Another note: because this repo doesn't commit its BUILD.bazel files, it's not possible to depend on the generated code even if you're using bazel. (I might be wrong since I'm newer to bazel)

**Comment by perotinus** [comment]
Generated code and BUILD files are now checked in.
