### ISSUE TITLE
CRD definition is broken on kube 1.11.1 cluster

### ISSUE THREAD

**Issue by patrickshan** [kubernetes/cluster-registry#255]
/sig multicluster
 when applying the crd config to a kube 1.11.1 cluster, it will error out with this message:
```
$ kubectl apply -f cluster-registry-crd.yaml
error: error validating "cluster-registry-crd.yaml": error validating data: [ValidationError(CustomResourceDefinition.status): missing required field "conditions" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.CustomResourceDefinitionStatus, ValidationError(CustomResourceDefinition.status): missing required field "storedVersions" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.CustomResourceDefinitionStatus]; if you choose to ignore these errors, turn validation off with --validate=false
```

Currently we worked around the issue by updating CRD with this change although we are not quite sure if that's the right way to fix it:
```
-  conditions: null
+  conditions: []
+  storedVersions: []
```

**Comment by embik** [comment]
Hey @perotinus any update here? It's still broken on Kubernetes 1.11.4 and the issue going stale isn't exactly correct. We're looking into cluster-registry as a "datastore" for cluster information and I wonder what the current state of the project is here.
