### ISSUE TITLE
Dead project?

### ISSUE THREAD

**Issue by merlindorin** [kubernetes/cluster-registry#288]
Hi,

We are working on a federated system and we really appreciate all the work done in the SIG multi-cluster.

The cluster registry is in alpha since 2018, should we rely on this project? The api is pretty simple, there is any reason why the version is still in alpha level? (maybe it's due to related projects, etc.)

Thx guys.

/sig multicluster

**Comment by RainbowMango** [comment]
@merlindorin 
There is an opening discussion on [this issue](https://github.com/kubernetes/org/issues/1499#issuecomment-656888759), and also a survey for collect cluster registry use cases.

SIG-Multicluster will decide should this project be archived or not after collecting enough use cases. You are welcome to address your use cases.

**Comment by merlindorin** [comment]
Thx for the quick reply, will check that ;)
