### ISSUE TITLE
Create a helm chart to deploy the cluster-registry

### ISSUE THREAD

**Issue by pmorie** [kubernetes/cluster-registry#38]
It would be extremely useful to have a helm chart to deploy the cluster-registry and the apiservice resource to add it into the aggregator.

**Comment by pmorie** [comment]
@onyiny-ang is going to look at this.

**Comment by perotinus** [comment]
Thanks @onyiny-ang!

I'm looking forward to seeing this! Hopefully the Helm chart won't diverge too much from what crinit is doing, and we'll be able to document it well enough that users understand how to set up the registry the way they want.

**Comment by onyiny-ang** [comment]
@perotinus I will do my best and am completely new to Helm charts so bear with me!

**Comment by perotinus** [comment]
@onyiny-ang @pmorie Any updates on this? I remember in the last SIG meeting there were some concerns raised around whether a Helm chart would be able to support the authentication setup that was necessary.

**Comment by pmorie** [comment]
@perotinus If you know all the CNs you need to sign a certificate with for the cluster registry, then you should be able to write a helm chart that does everything you need.

However, I don't think that it will be possible to write a helm chart that signs a certificate for a dynamically allocated IP for an external load balancer.  The IP address would be one of the CNs you would need to know in advance to sign the certificate for the cluster registry with.

Does that make sense?

**Comment by font** [comment]
@perotinus We are limited by the fact that we are looking to support a cluster registry deployed both as an aggregated and standalone API server. The helm chart would work for the aggregated API server use-case, or the standalone when using NodePort only. But as @pmorie states, a helm chart would not work when using an external load balancer.

**Comment by perotinus** [comment]
@font @pmorie Thanks for those explanations, that makes a lot of sense.

Do you think there's value in pursuing a Helm chart for aggregated deployments (and NodePort-based independent deployments)? It seems reasonable that people would want these, it is probably an easier ramp-up path than the tool, and I'm not opposed to having multiple supported deployment models as long as there isn't then pressure to support *every* deployment model specifically.

**Comment by perotinus** [comment]
Also, I imagine that an external load balancer would work if you could provide (or predict) its DNS name?

**Comment by font** [comment]
@perotinus I imagine there may be requests to support a Helm chart for the CR - especially if the aggregated deployment model well supported by a Helm chart ends up being the most common. Additionally, we'd probably have to support all the deployment models for which we create tools so we should be careful.

Yes, I think that would work if we knew the external load balancer IP/DNS CNAME before signing the certificate. Or if Helm adds the ability to store state between different chart dependencies such that it could wait for that load balancer IP before signing.

Additionally, we may want to look at helm plugins to see if something like this is doable.

**Comment by pmorie** [comment]
Closing for now.  Doesn't look like this is tractable as a solution for crinit.
