### ISSUE TITLE
Repurpose kubefed to join/unjoin clusters

### ISSUE THREAD

**Issue by madhusudancs** [kubernetes/cluster-registry#4]
@perotinus has repurposed `kubefed` (now called `crinit` in this repository) to simplify cluster registry installation in a host Kubernetes cluster. Add support to crinit so that it could be used to register clusters to or deregister clusters from a cluster registry.

cc @G-Harmon @perotinus @csbell @nikhiljindal

**Comment by perotinus** [comment]
@madhusudancs and I chatted about this a bit offline. For now, I think `kubectl` is adequate for this use case, since it supports CRUD operations on clusters in a cluster registry.
