### ISSUE TITLE
Implement non-delegated authorization

### ISSUE THREAD

**Issue by perotinus** [kubernetes/cluster-registry#46]
The cluster registry should have a way to handle authorization when it is not being run as a delegated API server. It doesn't seem ideal to implement the RBAC APIs in the cluster registry, given the potential for confusion and mismatches in implementing an API for a k8s object. One potential approach here is to use an authenticating/authorizing proxy.

Split from #8, which is tracking work for delegated authorization.

**Comment by perotinus** [comment]
Thinking about this a bit more. It looks like there are several different authorization modes in core k8s:

- `AlwaysAllow`: currently what's implemented by default
- `AlwaysDeny`: not implemented, but easy to implement
- `ABAC`: probably possible to implement, but all the code appears to be in core Kubernetes
- `Webhook`: the most promising option IMO, since it has code in the generic `apiserver` library, and the cluster registry would only need glue.
- `RBAC`: not usable in standalone mode, because the cluster registry does not expose the RBAC APIs. If RBAC is desired, the best thing to do is to aggregate to an existing k8s API server and use that API server's authz support
- `Node`: not relevant here since there are no nodes controlled by the cluster registry

Therefore, I propose that the standalone cluster registry only implement the `AlwaysAllow`, `AlwaysDeny` and `Webhook` modes. Of these, only the latter is at all complicated.

**Comment by perotinus** [comment]
@font @madhusudancs @pmorie, do you agree with my assessment above? If so, someone can start implementing whatever is necessary.

**Comment by madhusudancs** [comment]
Ok for now and no objections to what you have proposed here. Except for the fact that we have all agreed before that there needs to be a mechanism for restricted views, i.e. when a user A asks for a list of clusters, they should only get the list of clusters that user A is allowed to see.

**Comment by font** [comment]
Agree with @madhusudancs. I think we'd have to use RBAC which would work only in an aggregated deployment.

**Comment by perotinus** [comment]
That's a good point. I would think that the `Webhook` authz mode would handle this, but someone will need to look into that in more detail.
