### ISSUE TITLE
Update rules_go to 0.6.0

### ISSUE THREAD

**Issue by font** [kubernetes/cluster-registry#56]
Update cluster-registry rules_go to 0.6.0. This should help enable bazel debug builds enabled by https://github.com/bazelbuild/rules_go/pull/743.

**Comment by perotinus** [comment]
This is being handled incidentally in #57. The version there is not the tagged 0.6.0, but is a revision that includes all changes in 0.6.0.

**Comment by font** [comment]
Sounds good - we can close this once it's merged.

**Comment by perotinus** [comment]
Fixed by #57.
