### ISSUE TITLE
Figure out a coherent strategy for updating vendored dependencies

### ISSUE THREAD

**Issue by perotinus** [kubernetes/cluster-registry#59]
Based on @ericchiang's comment (https://github.com/kubernetes/cluster-registry/pull/58#issuecomment-340890545).

`dep` is currently not quite ready for use with all of Kubernetes, and using it will potentially expose us to incompatibilities; however, there is activity in other k8s repos to improve `dep` support. Since updating vendored deps is not a common activity, it's not critical to have it be a completely smooth experience, but it should also not be so arcane and messy as to be undoable. We need to evaluate further.

**Comment by pmorie** [comment]
Glide is also not perfect at all, which is more a property of glide (my subjective opinion / ignorance here) than a property of kubernetes.

I do think that there are gaps to be closed in k8s, in particular WRT api-machinery git tags.

**Comment by perotinus** [comment]
Note that this issue is no longer applicable because of the CRD migration done in #225, which removes `crinit` and the standalone API server.
