### ISSUE TITLE
Connect the repo to Reviewable

### ISSUE THREAD

**Issue by G-Harmon** [kubernetes/cluster-registry#6]
Hey Jonathan,
We looked at this yesterday. Do you want to connect the cluster-registry up to Reviewable?

"Please connect this repo at https://reviewable.io/repositories so that all PRs get linked to reviews. Thanks!"

**Comment by perotinus** [comment]
I'm not sure. Personally I'm not a huge fan of Reviewable.

If people are in favor or against using Reviewable, please bump this issue and we can decide based on feedback.
