### ISSUE TITLE
crinit tool name and interface should be considered more carefully

### ISSUE THREAD

**Issue by perotinus** [kubernetes/cluster-registry#68]
From https://github.com/kubernetes/cluster-registry/pull/65#issuecomment-342322999, we should consider how the `crinit` tool can be named and how its interface should be organized.

- renaming `crinit` to `kubecr` (credit @font for the name) or something else
- renaming/regrouping the subcommands to prepare for adding more commands to interact with a cluster registry. This isn't necessarily straightforward, since the tool is intended to support both aggregated and standalone deployments, each of which may have different create/update/delete operations, which may imply a three level nesting of (e.g.) `kubecr <aggregated|standalone> <init|update|delete>`.

I think this is something we'd want to do on a beta timeframe, since at that point we will be expecting the tool's interface not to change significantly.

**Comment by perotinus** [comment]
Strawman proposal:

- rename `crinit` to `kubecr`
- add an `init` subcommand to the `standalone` and `aggregated` commands. This `init` command will work like the current `aggregated` and `standalone` commands, and having it will give us room to add `delete`,`update`, etc.

@font @madhusudancs @pmorie Thoughts?

**Comment by madhusudancs** [comment]
Sounds reasonable to me. I don't like `kubecr` though. Is it supposed to be an acronym or just an abbreviation? But that's subjective and you can completely ignore me.

**Comment by font** [comment]
Sounds good to me.

**Comment by perotinus** [comment]
Excellent! I'll post a PR for the subcommand changes.

Does anyone have a good idea for a command name? I'm not really a fan of keeping `crinit` as the tool may evolve to support upgrading/deleting/etc.

**Comment by perotinus** [comment]
#139 adds subcommands. At this point, I think all that remains is to decide about the tool name.

Personally, I can't think of anything better than `kubecr`: it matches the pattern of kubernetes tools being `kube` plus a few descriptive letters, it doesn't imply much about what the tool will do, and it's not that long.

**Comment by perotinus** [comment]
Pushing to the next milestone, since the interesting part of this (having aggregated and standalone subcommands) is already done.

**Comment by perotinus** [comment]
Given the conversations around the name of this API, I think is better deferred. I'd rather not rename the tool to `kubecr` or some such, and then rename the API such that the tool name needs to be changed again. I think this can wait for a stable release; we don't expect people to use this tool in scripts, so changing the name should not be a huge issue during the beta->stable timeframe.

**Comment by perotinus** [comment]
Note that this issue is no longer applicable because of the CRD migration done in #225, which removes `crinit` and the standalone API server.
