### ISSUE TITLE
clusterregistry apiserver delegated vs standalone personality should be considered

### ISSUE THREAD

**Issue by font** [kubernetes/cluster-registry#69]
From [#8 (comment)](https://github.com/kubernetes/cluster-registry/issues/8#issuecomment-341819091):

How do we want to handle the different personalities that clusterregistry will assume when running as a delegated vs standalone apiserver?

Some things that will need to be addressed:

- Authn model: currently CR has built-in authn model. Will also need to delegate to core k8s apiserver. Need to allow both.
- Authz model: currently CR has always-allow authz model. Will also need to delegate to core k8s apiserver. Need to allow both.
- Necessary flags: handling common and mutually exclusive flags for standalone vs delegated
- Other stuff?

Some possible options:

- Add extra flag error checking. Possible confusion when user specifies combinations that are not compatible. This assumes we have several mutually exclusive options. It's not clear that we do yet but may in the future.
  - Roughly 8 for authn standalone and 8 for authn delegated. 
- Do we want to add new sub-commands to handle the different flags that could then trigger different paths for the authn/authz setup? This would seem strange for an apiserver. Are there any other apiservers doing this?
  - This could be something similar to hyperkube where the first argument specifies which "personality" to execute.
- Two separate binaries for delegated vs standalone. Probably try to avoid this unless we follow a hyperkube type model.
- Other options?

**Comment by perotinus** [comment]
Given the changes in #120, @font and I believe that the best way to handle the two personalities is to have subcommands. So, `clusterregistry standalone [flags]` and `clusterregistry aggregated [flags]`. This works around the issue where the standalone and aggregated personalities have different authn/authz requirements, but with some flags with shared names, and should make it easier for someone to understand which flags apply to which usage of the tool. This is not necessarily something that other API servers are doing, but it does have some similarities with how `hyperkube` works (as @font mentioned above).

@pmorie @madhusudancs do you have any concerns with/thoughts about this approach? If not, we should start implementing it.

/assign @pmorie @madhusudancs

**Comment by madhusudancs** [comment]
No concerns. +1 to splitting it into subcommands.

`hyperkube`'s case is very different though. `hyperkube` just serves as an anchor point for completely different binaries. But anyway, that distinction is not very relevant here though.

**Comment by perotinus** [comment]
@font @pmorie I'm planning to take this on tomorrow if I don't hear any objections.

**Comment by perotinus** [comment]
@font Ivan is going to take this on.

**Comment by perotinus** [comment]
Fixed in #163.
