### ISSUE TITLE
Publish reference docs for cluster registry API server and crinit

### ISSUE THREAD

**Issue by madhusudancs** [kubernetes/cluster-registry#71]
Cluster registry users need reference docs for both API server and crinit binaries. The help text accessible through `--help` command line flag serves its purpose, but it is also extremely valuable to have it on the web so that it is indexed and made quickly accessible through search engines. It saves users from downloading the binaries and running `--help` every time they want to look up something really quick.

cc @perotinus @font @pmorie

**Comment by perotinus** [comment]
#194 adds reference docs for the API.

**Comment by madhusudancs** [comment]
Can we please prioritize hosting the generated html for the ref docs somewhere? It's great that we have it now, but every time I want to use it I download the html file and open it in my browser. This is just too painful. Can we put this at [k8s.io/docs/reference](k8s.io/docs/reference)? If we are not allowed to can we at least create a github page for it?

**Comment by font** [comment]
@madhusudancs They are hosted at https://kubernetes.github.io/cluster-registry/api_reference.html. We should add a link to our github page from the github repo.

I've also discussed with SIG-Docs about getting our docs hosted at k8s.io and they are very interested in that once we are at least in beta. We also need to figure out the renaming/split of the repo. Then eventually we should be able to host them at k8s.io.

**Comment by perotinus** [comment]
Note that this issue is no longer applicable because of the CRD migration done in #225, which removes `crinit` and the standalone API server.
