### ISSUE TITLE
Working integration with Federation

### ISSUE THREAD

**Issue by perotinus** [kubernetes/cluster-registry#83]
/sig multicluster

The API should be stable enough at this point to support replacing the Federation cluster API with the cluster registry. The details of this integration will need some design: it's not clear whether the Federation API server will aggregate the cluster registry, or include the API types directly, or something else entirely.

From https://github.com/kubernetes/community/blob/master/contributors/design-proposals/multicluster/cluster-registry/project-design-and-plan.md#beta

**Comment by pmorie** [comment]
Has anyone yet investigated whether FCP works as an aggregated API?

**Comment by pmorie** [comment]
I would imagine that it does not work, personally.

**Comment by perotinus** [comment]
Since https://github.com/kubernetes-sigs/federation-v2 is using the cluster registry and Federation v1 is deprecated, I'm going to close this issue.

/close
