### ISSUE TITLE
Contributor documentation written

### ISSUE THREAD

**Issue by perotinus** [kubernetes/cluster-registry#88]
/sig multicluster

This is already at least partially done, but could be improved.

Some ideas:

- examples of how to use the generated clients
- explanation of the code structure
- all packages have package-level documentation

Feel free to add more ideas!

From https://github.com/kubernetes/community/blob/master/contributors/design-proposals/multicluster/cluster-registry/project-design-and-plan.md#alpha-targeting-late-q4-17

**Comment by perotinus** [comment]
Thinking about this some more, I think the second and third bullet points can be partially combined: if each package that has go code is documented, then all that remains is to add README.md files for packages that do not contain Go code and to add a note to that effect.

**Comment by perotinus** [comment]
@pmorie @madhusudancs @font, do you have any other ideas about things we could put in the contributor documentation?

If not, now that we have package-level docs everywhere, I think we have a good enough explanation of the code structure via godoc. The last thing that remains is an example of using the cluster client, which I think can be done with a simple command line tool that uses the `cliendcmd` library to get a client and print out some information about clusters.

**Comment by madhusudancs** [comment]
I don't think it is is necessary to document the code structure at this point. The codebase is rapidly evolving and anything we document at this point will soon be obsolete. And as you mentioned, it's redundant due to godoc.

**Comment by madhusudancs** [comment]
I think one topic that's worth pointing to or writing about is the required bot interaction in the PR flow. I don't know if it's well documented in some other kubernetes repo in a way that you can just point to a subset of what we use in this repo.

**Comment by perotinus** [comment]
@madhusudancs Good point, I'll add a note about that to the developer docs with a link to the page with the bot commands. Thanks!

**Comment by perotinus** [comment]
@font Ivan, I think you were going to look at doing a simple example of using the clusterregistry client?

**Comment by font** [comment]
@perotinus Yes, I will work on this.

**Comment by perotinus** [comment]
Closing this, since we do have contributor docs. I'll file another issue for the example.
