### ISSUE TITLE
User documentation drafted

### ISSUE THREAD

**Issue by perotinus** [kubernetes/cluster-registry#89]
/sig multicluster

We should have a draft of user documentation for how to bootstrap/set up/use a cluster registry. This should probably include some examples as well.

From https://github.com/kubernetes/community/blob/master/contributors/design-proposals/multicluster/cluster-registry/project-design-and-plan.md#alpha-targeting-late-q4-17

**Comment by perotinus** [comment]
Closing #11 in favor of this.

**Comment by font** [comment]
@perotinus I think the milestone for this was meant to be v0.1 (Alpha)
