### ISSUE TITLE
Cross-platform client and server binaries

### ISSUE THREAD

**Issue by perotinus** [kubernetes/cluster-registry#98]
/sig multicluster

From https://github.com/kubernetes/community/blob/master/contributors/design-proposals/multicluster/cluster-registry/project-design-and-plan.md#stable-targeting-mid-q2-18

**Comment by perotinus** [comment]
bazel 0.8.0 and the newest version of `rules_go` support cross-compilation. Unfortunately, there are some issues with `kubernetes/repo_infra` that prevent us from migrating to them immediately. If this becomes a major issue, we can find workarounds, but in the interest of not doing extra work, I think we can wait for `repo_infra` to be updated.

**Comment by perotinus** [comment]
https://github.com/kubernetes/repo-infra/pull/52 has the necessary `repo-infra` changes.

**Comment by ixdy** [comment]
I was waiting on kubernetes/repo-infra/pull/52 until kubernetes/kubernetes/pull/56820 was ready for merge, in case we otherwise needed to bump repo-infra in k/k, but if this is blocking you I can go ahead and merge.

**Comment by ixdy** [comment]
Note that bazel / rules_go cross-compilation currently only works for pure-Go binaries (i.e. `CGO_ENABLED=0`). cgo-dependent Go binaries are a work in progress.

**Comment by perotinus** [comment]
@ixdy This is not a high priority at the moment, so I think we can wait until the k8s change goes in. I'd like to have cross-compilation working sometime early next year.

**Comment by ixdy** [comment]
So does kubernetes/kubernetes, so that seems like a nice alignment of schedules. (Hopefully cgo cross compilation will work by then, too.)

**Comment by perotinus** [comment]
Note that this issue is no longer applicable because of the CRD migration done in #225, which removes `crinit` and the standalone API server.
